#' Synthetic whole-rock geochemical dataset
#'
#' Fifty synthetic whole-rock analyses across four volcanic rock types
#' (Basalt, Andesite, Dacite, Rhyolite). Major oxides are in wt % and
#' trace elements in ppm. Generated with `set.seed(42)` for reproducibility.
#'
#' @format A data frame with 50 rows and 28 variables:
#' \describe{
#'   \item{Sample_ID}{Character. Sample identifier (WR-001 to WR-050).}
#'   \item{rock_type}{Character. Rock classification: Basalt, Andesite, Dacite, or Rhyolite.}
#'   \item{SiO2, TiO2, Al2O3, Fe2O3, FeO, MnO, MgO, CaO, Na2O, K2O, P2O5}{
#'     Numeric. Major oxide concentrations in wt \%.}
#'   \item{Ni, Cu, Zn, Rb, Sr, Y, Zr, Nb, Ba}{
#'     Numeric. Trace element concentrations in ppm.}
#'   \item{La, Ce, Nd, Sm, Eu, Gd, Yb, Lu}{
#'     Numeric. Rare earth element concentrations in ppm.}
#' }
#' @source Synthetically generated by `data-raw/generate_testdata.R`.
"whole_rock_data"


#' Synthetic laser ICP-MS element map
#'
#' A 50 × 50 grid (2 500 points) simulating a laser-ablation element map.
#' A synthetic ore zone with elevated Cu, Fe, Au, and S is embedded near
#' coordinates (100, 100). Generated with `set.seed(42)`.
#'
#' @format A data frame with 2 500 rows and 10 variables:
#' \describe{
#'   \item{x, y}{Numeric. Spatial coordinates in micrometres.}
#'   \item{Fe_ppm}{Numeric. Iron concentration in ppm.}
#'   \item{Cu_ppm}{Numeric. Copper concentration in ppm.}
#'   \item{Zn_ppm}{Numeric. Zinc concentration in ppm.}
#'   \item{Pb_ppm}{Numeric. Lead concentration in ppm.}
#'   \item{As_ppm}{Numeric. Arsenic concentration in ppm.}
#'   \item{S_ppm}{Numeric. Sulphur concentration in ppm.}
#'   \item{Au_ppb}{Numeric. Gold concentration in ppb.}
#'   \item{Bi_ppm}{Numeric. Bismuth concentration in ppm.}
#' }
#' @source Synthetically generated by `data-raw/generate_testdata.R`.
"laser_map_data"


#' Synthetic PGE assay dataset with below-detection-limit values
#'
#' Forty synthetic PGE / noble-metal assay results. A fraction of values fall
#' below the instrument detection limit and are stored as strings such as
#' `"<0.05"`. Use with [Random_Number_Imputer()] to replace them with
#' uniformly distributed random values below the detection threshold.
#'
#' @format A data frame with 40 rows and 5 variables:
#' \describe{
#'   \item{Sample_ID}{Character. Sample identifier (DL-001 to DL-040).}
#'   \item{Au_ppb}{Character. Gold concentration in ppb; BDL values as "<0.05".}
#'   \item{Pd_ppb}{Character. Palladium concentration in ppb; BDL values as "<0.10".}
#'   \item{Pt_ppb}{Character. Platinum concentration in ppb; BDL values as "<0.10".}
#'   \item{Ag_ppb}{Character. Silver concentration in ppb; BDL values as "<0.50".}
#' }
#' @source Synthetically generated by `data-raw/generate_testdata.R`.
"detection_limit_data"
